In [0]:
import numpy as np
import pandas as pd
import keras
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Dropout, Flatten, Dense
from keras.optimizers import SGD
from keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import roc_auc_score
from keras.layers import Input
from keras.models import Model
import cv2 
from keras.preprocessing import image

In [102]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [103]:
%cd /content/drive/My Drive/Trained_Models

/content/drive/My Drive/Trained_Models
/content/drive/My Drive/Trained_Models


In [0]:
#img=cv2.imread('AI-developer-project-part-2-enhancing-distracted-driver-behavior-figure1.jpg')
img=cv2.imread('images-2.jpeg')
#img=cv2.imread('Unknown.jpeg')
#img=cv2.imread('images.jpeg')
img=cv2.resize(img,(32,32))
img=np.expand_dims(img, axis=0)

Transforming the image according to the first model

In [0]:
train_datagen = ImageDataGenerator(
    rescale = 1./255,
    shear_range = 0.4, 
    zoom_range = 0.3,
    horizontal_flip = True,
    validation_split=0.2) 

Importing the Trained model

In [106]:
from keras.models import model_from_json
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
loaded_model.load_weights("model.h5")
print("Loaded model from disk")

Loaded model from disk


In [0]:
#newimg=image.img_to_array(img)
#output=loaded_model.predict(newimg.reshape(1,32,32,3))
output=loaded_model.predict(img)


In [108]:
print(output)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [126]:
for i in range(len(output[0])):
  if(output[0][i]==1.0):
    print(output[0][i])
    print("Correct")
    if(i==0):
      print("Driving Safely")
      break
    elif(i==1):
      print("Texting with the right hand")
      break
    elif(i==2):
      print("Talking on the phone with right hand")
      break
    elif(i==3):
      print("Texting with the left hand")
      break
    elif(i==4):
      print("Talking on the phone with left hand")
      break
    elif(i==5):
      print("Operation on the Radio")
      break
    elif(i==6):
      print("Drinking")
      break
    elif(i==7):
      print("Reaching Behind")
      break
    elif(i==8):
      print("Hair and Makeup")
      break
    elif(i==9):
      print("Talking with Passenger")
      break

1.0
Correct
Talking with Passenger
9


In [110]:
from keras.models import model_from_json
json_file = open('model1.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model1 = model_from_json(loaded_model_json)
loaded_model1.load_weights("model1.h5")
print("Loaded model from disk")

Loaded model from disk


In [0]:
output1= loaded_model1.predict(img)

In [112]:
print(output1)

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


In [128]:
for j in range(len(output1[0])):
  if(output1[0][j]==1.0):
    print(output1[0][j])
    print("Correct")
    if(j==0):
      print("Driving Safely")
      break
    elif(j==1):
      print("Texting with the right hand")
      break
    elif(j==2):
      print("Talking on the phone with right hand")
      break
    elif(j==3):
      print("Texting with the left hand")
      break
    elif(j==4):
      print("Talking on the phone with left hand")
      break
    elif(j==5):
      print("Operation on the Radio")
      break
    elif(j==6):
      print("Drinking")
      break
    elif(j==7):
      print("Reaching Behind")
      break
    elif(j==8):
      print("Hair and Makeup")
      break
    elif(j==9):
      print("Talking with Passenger")
      break

1.0
Correct
Talking with Passenger


In [114]:
from keras.models import model_from_json
json_file = open('model2.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model2 = model_from_json(loaded_model_json)
loaded_model2.load_weights("model2.h5")
print("Loaded model from disk")

Loaded model from disk


In [0]:
output2=loaded_model2.predict(img)

In [116]:
print(output2)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [129]:
for k in range(len(output2[0])):
  if(output2[0][k]==1.0):
    print(output2[0][k])
    print("Correct")
    if(k==0):
      print("Driving Safely")
      break
    elif(k==1):
      print("Texting with the right hand")
      break
    elif(k==2):
      print("Talking on the phone with right hand")
      break
    elif(k==3):
      print("Texting with the left hand")
      break
    elif(k==4):
      print("Talking on the phone with left hand")
      break
    elif(k==5):
      print("Operation on the Radio")
      break
    elif(k==6):
      print("Drinking")
      break
    elif(k==7):
      print("Reaching Behind")
      break
    elif(k==8):
      print("Hair and Makeup")
      break
    elif(k==9):
      print("Talking with Passenger")
      break

1.0
Correct
Operation on the Radio


In [118]:
from keras.models import model_from_json
json_file = open('classifier.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_classifier = model_from_json(loaded_model_json)
loaded_classifier.load_weights("classifier.h5")
print("Loaded model from disk")

Loaded model from disk


In [0]:
#img2=cv2.imread('AI-developer-project-part-2-enhancing-distracted-driver-behavior-figure1.jpg')
#img2=cv2.imread('images.jpeg')
#img2=cv2.imread('Unknown.jpeg')
img2=cv2.imread('images-2.jpeg')
img2=cv2.resize(img2,(77,77))
img2=np.expand_dims(img2, axis=0)
output3=loaded_classifier.predict(img2)

In [120]:
print(output3)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [130]:
for l in range(len(output3[0])):
  if(output3[0][l]==1.0):
    print(output3[0][l])
    print("Correct")
    if(l==0):
      print("Driving Safely")
      break
    elif(l==1):
      print("Texting with the right hand")
      break
    elif(l==2):
      print("Talking on the phone with right hand")
      break
    elif(l==3):
      print("Texting with the left hand")
      break
    elif(l==4):
      print("Talking on the phone with left hand")
      break
    elif(l==5):
      print("Operation on the Radio")
      break
    elif(l==6):
      print("Drinking")
      break
    elif(l==7):
      print("Reaching Behind")
      break
    elif(l==8):
      print("Hair and Makeup")
      break
    elif(l==9):
      print("Talking with Passenger")
      break

1.0
Correct
Talking with Passenger


## Majority Voting for the ensemble

In [0]:
accuracy1=0.8780679363856118
accuracy2=0.1842
accuracy3=0.9652071470669391
accuracy4=0.9353622619304773

In [0]:
maps={0:'Driving Safely',1:'Texting with the right hand',2:'Talking on the phone with right hand',3:'Texting with the left hand',4:'Talking on the phone with left hand',5:'Operation on the Radio',6:'Drinking',7:'Reaching Behind',8:'Hair and Makeup',9:'Talking with Passenger'}

In [143]:
out1=output[0]*accuracy1
out2=output1[0]*accuracy2
out3=output2[0]*accuracy3
out4=output3[0]*accuracy4
print(out1)
print(out2)
print(out3)
print(out4)

[0.        0.        0.        0.        0.        0.        0.
 0.        0.        0.8780679]
[0.     0.     0.     0.     0.     0.     0.     0.     0.     0.1842]
[0.         0.         0.         0.         0.         0.96520716
 0.         0.         0.         0.        ]
[0.        0.        0.        0.        0.        0.        0.
 0.        0.        0.9353623]


In [144]:
final_result= out1+out2+out3+out4

prediction_confidence=max(list(final_result))

prediction_class_numeral=list(final_result).index(max(list(final_result)))

#create a string and numeral map for mapping each index to the class

final_class=maps[prediction_class_numeral]


print('the driver is: ',final_class)

the driver is:  Talking with Passenger
